frase = 'Curso em Vídeo Python'
print(frase[3])
print(frase[3:13])
print(frase[:13])
print(frase[1::2])
print(frase[::2])
print(frase.count('o'))
print(len(frase))
print(frase.replace('Python', 'Android'))
print(frase[0])
print('Curso' in frase)
print(frase.find('Vídeo'))
print(frase.lower())
print(frase.split())